### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by alexellis**
Your Dockerfile was broken and a bit out of date. Here's an updated version.

### CODE REVIEW

**Comment by tpruvot** [comment]
made my own one, tx for the notice

**Comment by alexellis** [comment]
You should really combine the steps like I did in my submission. Especially apt-get update and install. You don't want these to get cached separately. I.e. use &&

**Comment by tpruvot** [comment]
the updated apt should be common with most other repos, not the second

**Comment by tpruvot** [comment]
Do you know a way to reduce the final size ? like removing unrequired build stuff after the build maybe ?

**Pull request closed without merging**
