### PR TITLE
Add ARM support

### PR DESCRIPTION
**Pull request by caiotoledo**

### CODE REVIEW

**Comment by caiotoledo** [comment]
Tested on Beaglebone Black

**Comment by tpruvot** [comment]
could you try to move that to scryptjane/scrypt-jane-portable.h (at the end)

**Comment by BrazilianGirl** [comment]
can you add support to ARM7  to mining RVNCOIN? thanks !

**Comment by caiotoledo** [comment]
@tpruvot moved!

**Comment by caiotoledo** [comment]
@BrazilianGirl Could you create a issue in my repository about this? After @tpruvot aprove my pull request I could work on that.

**Comment by paperclip731** [comment]
I cannot get cpuminer-zoin to compile adding in the neon instructions for ARM.
Looks loke errors in scrypt-jane.c
Undefined reference to ‘detect_cpu’
Collect2: error ld retirned 1exit atatus
Makefile:869: recipe for target ‘cpuminer’ failed

**Comment by caiotoledo** [comment]
@paperclip731 cpuminer-zoin do not have this commit.
You could try to implement it in cpuminer-zoin, as I did in this pull request.
Could you test it?

**Comment by paperclip731** [comment]
I am pretty bad in linux but i can try, what doni need to do?

**Pull request merged**
